### ISSUE TITLE
Falha ao criar notificação

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/notification-service#152]
Verificar e corrigir o erro que impede que seja emitido uma mensagem para o canal websocket no método **enviarMensagem** do arquivo **NotificacaoFormulario.vue**

**Comment by vinnyfs89** [comment]
Dica: observar a definição do objeto **websocket**

**Comment by guiamado** [comment]
Issue Resolvida na branch feature/migrando-notificacao-badge, onde estará contido no Pull Request #156.
