### ISSUE TITLE
Geração de Relalório - Release 1

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/notification-service#184]

**Comment by guiamado** [comment]
# Release 1

## Módulo Notificação
- Criação da Notificação
- Visualização de Notificações vinculadas a cada Usuário
- Deletar Notificações vinculadas ao Usuário
- Sincronização das Notificações com o Sininho
- Ler Notificções que chegam no Sininho

## Módulo de Plataformas
- Criação de Plataformas
- Edição do estado da Situação da Plataforma
- Deletar Plataformas

## Módulo de Sistemas
- Criação de Sistemas
- Edição de Sistemas
- Deletar Sistemas

## Módulo de Mensagens
- Criação de Mensagens com vínculos à um sistema e plataformas desejadas
- Visualização das Mensagens mais recentes
- Edição do corpo da Mensagem
- Deletar Mensagem

## Módulo de Contas
- Criação de contas com ao menos 1 vínculo de sistemas, opção de ser ativo e admnistrador.
- Edição da Conta, assim como vínculos de sistemas
- Deletar Contas específicas, não sendo do próprio usuário

## JWT
- Criação de Middleware para verificação de token, administrador, tempo de expiração
- Validação da Token em rotas
- Verificação em componentes da token ao fazer requisição e a possibilidade de verificar se o usuário é administrador

## Estilo de Código
- Utilização do ESLint do Airbnb para padronização e qualidade do código no frontend
- Utilização do PHPCS e PHPMD para padronização e qualidade do código no backend

## Menu Lateral
- Visualização do usuário logado
- Acessar parte das Notificações
- Acesso à parte da administração do Sistema
- Saída do Sistema
- Informações Sobre o Sistema

**Comment by vinnyfs89** [comment]
@guiamado  sobre a issue 184 eu substituiria de Estilo de Código por Qualidade de Código


E em menu lateral colocaria "Criação do componente de menu Lateral"

**Comment by guiamado** [comment]
Feito!
